### ISSUE TITLE
Rendering Screen crash in TSMP

### ISSUE THREAD

**Issue by fzzyhmstrs** [EndLone/MCDE#25]
Hi! Was loading into the new version 3.0, and hit the following crash when I moused over my crossbow to move it into my offhand. Looks like there is some NBT metadata that is based on `Growing`, which we have now disabled in the MCDW config. That means that Growing wasn't registered, so the `get` below fails and returns null.

```
Reported exception thrown!
net.minecraft.util.crash.CrashException: Rendering screen
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:954)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.enchantment.Enchantment.getMaxLevel()" because the return value of "net.minecraft.registry.Registry.get(net.minecraft.util.Identifier)" is null
	at net.minecraft.item.ItemStack.handler$ggi000$mcde$appendEnchantmentLines(ItemStack.java:14661)
	at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:656)
	at net.minecraft.client.gui.screen.Screen.getTooltipFromItem(Screen.java:225)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.getTooltipFromItem(HandledScreen.java:183)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.drawMouseoverTooltip(HandledScreen.java:178)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen.java:92)
	at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:110)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945)
	... 6 more
```

**Comment by Iamnotagenius** [comment]
How can I reproduce the issue?

**Comment by fzzyhmstrs** [comment]
The series of events we ran into

First, enchant an item in the Runic Table with an MCDX enchantment
Next, disable that enchantment in the MCDX configs.
Finally, relaunch and try to hover over the item with the now-missing disabled enchantment
